AWSTemplateFormatVersion: 2010-09-09

Description: Cvicenie 2 - EC2 instances & auto-scaling & load-balancing

###########################################################################
# Useful CloudFormation docs
###########################################################################
# functions:         https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html
# pseudo parameters: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html
# pseudo attributes: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-product-attribute-reference.html
# template sections: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
###########################################################################

Parameters:
  Project:
    Description: Project
    Type: String
    Default: FRI

  Environment:
    Description: Environment
    Type: String
    Default: lab

  NetworkStackName:
    Description: Name of parent network CloudFormation stack
    Type: String
    Default: basic-network

  OurPublicIp:
    Description: Our source public IPv4 address
    Type: String
    Default: '158.193.138.31/32'

  ImageId:
    Description: AMI (Amazon Machine Image) ID
    Type: String
    # more info: https://docs.amazonaws.cn/en_us/AWSEC2/latest/UserGuide/finding-an-ami.html
    # list of usable AMIs can be found in AWS console -> EC2 -> AMI Catalog
    # Amazon Linux 2 (HVM), Kernel 5.10, SSD Volume Type, us-east-1
    Default: ami-07761f3ae34c4478d

  InstanceType:
    Description: Instance type (number of vCPUs, memory, bandwidth, etc.)
    Type: String
    # "t3" family = General purpose, Intel Xeon Platinum 8000 series; "medium" size = 2 vCPUs, 4 GB memory
    # more info: https://aws.amazon.com/ec2/instance-types/t3/
    Default: t3.medium

  IamInstanceProfileName:
    Description: Instance IAM profile name
    Type: String
    # it's unique in each account. can be found in IAM service as AmazonSSMRoleForInstancesQuickSetup (part of Instance profile ARN)
    # e.g. c76725a1578383l3622172t1w333290784692-SsmRoleInstanceProfile-apue5UBzE6mA


Resources:
###########################################################################
### Part 1 - security groups (firewall) & SSH key pair
###########################################################################

  SecurityGroupForPublicInstance:
    Type: AWS::EC2::SecurityGroup
    Description: public sec group
    Properties:
      GroupDescription: Security group for public instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref OurPublicIp
          Description: allow HTTP traffic from VPC
        
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref OurPublicIp
          Description: allow SSH traffic from VPC

      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
        Description: allow HTTPS ALL
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
        Description: allow HTTP ALL
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: { Fn::ImportValue: !Sub '${NetworkStackName}-VpcCidr' }
        Description: allow SSH ALL
      VpcId: { Fn::ImportValue: !Sub '${NetworkStackName}-VpcId' }
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Environment}-public-instance